global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 30s

rule_files:
  - '/etc/prometheus/alerts.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'docker'
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:9323']
        labels:
          environment: 'homelab'

  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:8082']
        labels:
          environment: 'homelab'

  - job_name: 'alertmanager'
    metrics_path: /metrics
    static_configs:
      - targets: ['alertmanager:9093']
        labels:
          environment: 'homelab'

  - job_name: 'consul'
    metrics_path: /metrics
    static_configs:
      - targets: ['consul-exporter:9107']
        labels:
          environment: 'homelab'

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          environment: 'homelab'